### ISSUE TITLE
Record expression is not exposed

### ISSUE THREAD

**Issue by sebsheep** [the-sett/elm-syntax-dsl#1]
The record expressions are defined at: https://github.com/the-sett/elm-syntax-dsl/blob/2.1.3/src/Elm/CodeGen.elm#L537-L543 but not exposed!

Would it be possible to add this?

**Comment by rupertlssmith** [comment]
Good spot, I'll have a check through and see if I missed anything else too.

**Comment by rupertlssmith** [comment]
Ok, that released as version 2.2.0
