### ISSUE TITLE
escape sequence in `Elm.CodeGen.string` sometimes isn't escaped in pretty printed expression

### ISSUE THREAD

**Issue by lue-bird** [the-sett/elm-syntax-dsl#50]
While all the usual escape sequences like `Elm.CodeGen.string "\n"` or with `"\\"`, `"\t"` or `"\""` get printed as `"\n"`, `"\\"` and `"\t"`, `"\""`,
the same is not true for carriage return and backslash u{...} sequences:

```elm
Test.describe "escape sequence in `Elm.CodeGen.string` sometimes isn't escaped in pretty printed expression"
    [ Test.test "string with escaped carriage return is pretty printed correctly"
        (\() ->
            Elm.CodeGen.string "\u{000D}"
                |> Elm.Pretty.prettyExpression
                |> Pretty.pretty 100
                |> Expect.equal "\"\\r\""
        )
    , Test.test "string with escaped combo emoji is pretty printed correctly"
        (\() ->
            Elm.CodeGen.string "👩\u{200D}🚒"
                |> Elm.Pretty.prettyExpression
                |> Pretty.pretty 100
                |> String.toList
                |> Expect.equalLists ("\"👩\\u{200D}🚒\"" |> String.toList)
        )
    ]
```
the `elm-test` output is
```
✗ string with escaped carriage return is pretty printed correctly

    "\"\r\""
    ╷
    │ Expect.equal
    ╵
    "\"\\r\""

✗ string with escaped combo emoji is pretty printed correctly

    '"', '👩', '‍', '🚒', '"'
    ╷
    │ Expect.equalLists
    ╵
    '"', '👩', '\\', 'u', '{', '2', '0', '0', 'D', '}', '🚒', '"'
    
    The first diff is at index 2: it was `'‍'`, but `'\\'` was expected.
```

This was noticed by Ed Kelly in https://github.com/lue-bird/elm-review-documentation-code-snippet/issues/5

The fix would be recognizing and handling those in https://github.com/the-sett/elm-syntax-dsl/blob/master/src/Elm/Pretty.elm#L1784 which needs to check both
  - is it backslash r
  - is it not printable according to the isPrint in https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Char.html (used by elm-format https://github.com/avh4/elm-format/blob/c99aa91b1b239653185e55a2085bceebcd1b5c4b/elm-format-lib/src/ElmFormat/Render/Box.hs#L1978) which could be checked using https://dark.elm.dmy.fr/packages/miniBill/elm-unicode/latest/Unicode

**Comment by rupertlssmith** [comment]
Been a while since I looked at this, but I definitely remember problems with escaping unicode that were never fixed.

Will you be submitting a PR with a fix?

**Comment by lue-bird** [comment]
Sure, let me make a PR for this.
